### PR TITLE
Historic specs cleanups

### PR DESCRIPTION
**Pull request by haarg**
This fixes and cleans up a number of things in the historic meta documents.  It updates the license text and links to point to the specific versions that were relevant at publication time.  It also updates various internal links for changes in the pod spec.  And it updates various external links to point to active resources.

### CODE REVIEW

**Comment by dolmen** [comment]
Here are a few more fixes:
- `Gnu General Public License` => `GNU General Public License`
- `GPL` => `GNU GPL`

**Comment by haarg** [comment]
Fixing the capitalization seems sensible, but GPL is an accepted abbreviation of the license, so I don't see the need to change that in the places it is used on its own.

**Comment by karenetheridge** [comment]
(y)

**Comment by xdg** [comment]
Rebased and merged as 73a3106.  Thanks!

**Pull request closed without merging**
