### PR TITLE
Replace JSON::PP based _dclone with a simpler, faster _dclone.

### PR DESCRIPTION
**Pull request by kentfredric**
This sacrifices the ability to be made faster via an XS extension,
but gives the general audience ( who will by default be using PP for
    their JSON backend ) a significantly faster result.

Median Comparisions:
  JSON::XS based : 0.0003 per parse
  PurePerl Clone : 0.0007 per parse ( 2.3x slower than XS )
  JSON::PP based : 0.02   per parse ( 66x  slower than XS )

Raw Data and Graphs of the benchmarking:
- https://docs.google.com/spreadsheets/d/1kFrnFXJ0ZmtWlA56fk2BP6a8BF6uC_5_VQh2y70Ddq8/edit?usp=sharing
Benchmark Code:
- https://github.com/kentfredric/CPAN-Meta/tree/clonebench/benchmark

This in also reduces test suite run time by about 30%

### CODE REVIEW

**Comment by kentfredric** [comment]
Code mostly based on @neilbowers  Clone::PP module but left out the parts I didn't think necessary for this usecase ( either that or I probably misunderstood their purpose, so feedback on improvement necessary )

I don't expect it will be merged in its current form, but its a good start IMHO.

**Comment by kentfredric** [comment]
And also the legacy codepath is still there so you can opt for it if need be/comparison. That will probably get nuked prior to final merge, or at very least, the ENV var will get a less-dumb name.

And I'm not entirely sure we can `use Scalar::Util` here, @mohawk2 can probably give a good opinion though.

**Comment by mohawk2** [comment]
Yes, please avoid `Scalar::Util`.

**Comment by dagolden** [comment]
I suspect that the only objects we expect to encounter are version objects, which can just be stringified, so messing with reftype/blessed might be unnecessary in practice.

**Comment by kentfredric** [comment]
Replacing the blessed/UNIVERSAL trick with stringification for some bizarre reason causes test failures.

Looks like its also relying on the fact CPAN::Meta impements a TO_JSON function.

```
 prove -lvr t/merge.t t/meta-obj.t t/save-load.t 
t/merge.t ...... 
ok 1 - First result is as expected
ok 2 - Can merge in identical abstract
ok 3 - Trying to merge different author gives an exception
ok 4 - Exception looks right
ok 5 - Trying to merge different author gives an exception
ok 6 - Exception looks right
Can't use string ("CPAN::Meta=HASH(0x20ed060)") as a HASH ref while "strict refs" in use at /home/kent/perl/forks/CPAN-Meta/lib/CPAN/Meta/Merge.pm line 19.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 6.
Dubious, test returned 2 (wstat 512, 0x200)
All 6 subtests passed 
t/meta-obj.t ... 
ok 1 - the result of ->as_struct is unblessed
not ok 2 - ->as_struct (deep comparison)

#   Failed test '->as_struct (deep comparison)'
#   at t/meta-obj.t line 85.
#     Structures begin differing at:
#          $got = 'CPAN::Meta=HASH(0x1a99020)'
#     $expected = CPAN::Meta=HASH(0x1a99020)
not ok 3 - ->as_struct (is a deep clone)

#   Failed test '->as_struct (is a deep clone)'
#   at t/meta-obj.t line 86.
#          got: 'CPAN::Meta=HASH(0x1a99020)'
#     expected: anything else
Can't use string ("CPAN::Meta=HASH(0x1a99020)") as a HASH ref while "strict refs" in use at /home/kent/perl/forks/CPAN-Meta/lib/CPAN/Meta/Converter.pm line 1364.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/3 subtests 
t/save-load.t .. hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /home/kent/perl/forks/CPAN-Meta/lib/CPAN/Meta.pm line 612.
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
t/merge.t    (Wstat: 512 Tests: 6 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/meta-obj.t (Wstat: 65280 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/save-load.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=3, Tests=9,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.30 cusr  0.06 csys =  0.41 CPU)
Result: FAIL
```

**Comment by kentfredric** [comment]
This is the simplest thing I can do that passes tests, its a bit of a hack...

```perl
sub _dclone_pp {
  my ( $ref  ) = @_;
  return $ref unless my $reftype = ref $ref;

  local $_CLONE_DEPTH = defined $_CLONE_DEPTH ? $_CLONE_DEPTH - 1 : $DCLONE_MAXDEPTH;
  die "Depth Limit $DCLONE_MAXDEPTH Exceeded" if $_CLONE_DEPTH == 0;

  return [ map { _dclone_pp( $_ ) } @{$ref} ] if 'ARRAY' eq $reftype;
  return { map { $_ => _dclone_pp( $ref->{$_} ) } keys %{$ref} } if 'HASH' eq $reftype;

  if ( 'SCALAR' eq $reftype ) {
    my $new = _dclone_pp(${$ref});
    return \$new;
  }
  if ( 'CPAN::Meta' eq $reftype ) {
    return $ref->TO_JSON;
  }
  # Just stringify everything else
  return "$ref";
}
```

**Comment by kentfredric** [comment]
An alternative solution might be simply:

```diff
sub as_struct {
  my ($self, $options) = @_;
+  my $struct = _dclone($self);
-  my $struct = _dclone($self->TO_JSON);
  if ( $options->{version} ) {
    my $cmc = CPAN::Meta::Converter->new( $struct );
    $struct = $cmc->convert( version => $options->{version} );
  }
  return $struct;
}

```

This seems to circumvent call the paths that try to dclone this object.

**Comment by Leont** [comment]
> This is the simplest thing I can do that passes tests, its a bit of a hack...

I'd prefer actual loop detection.

> An alternative solution might be simply in CPAN::Meta

The whole TO_JSON is a bit silly when called like that, might as well rename it.

**Comment by xdg** [comment]
Rebased, amended and merged in 18d5dd6

See the commit log for details of the refinements I made.

**Pull request closed without merging**
