### PR TITLE
Prefer stringify over normal

### PR DESCRIPTION
**Pull request by JohnPeacock**
Ignore my stupid commit message; I mean prefer stringify() over normal()...

### CODE REVIEW

**Comment by dagolden** [comment]
We don't want `stringify` because it allows "v1.2".  We want the normal form, as mandated by CPAN::Meta::Spec.

**Comment by JohnPeacock** [comment]
That's unfortunate because the normal form isn't well defined for alpha versions (meaning that it is impossible to round-trip it).

**Comment by karenetheridge** [comment]
Is round-tripping an absolute necessity for all forms?

**Comment by dagolden** [comment]
For the purpose of CPAN::Meta, I don't think so.

On Tue, Jan 20, 2015 at 1:17 PM, Karen Etheridge <notifications@github.com>
wrote:

> Is round-tripping an absolute necessity for all forms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Perl-Toolchain-Gang/CPAN-Meta/pull/85#issuecomment-70703611>
> .
>



-- 
David Golden <xdg@xdg.me> Twitter/IRC: @xdg

**Pull request closed without merging**
